### ISSUE TITLE
他只会回答:星火大模型正在思考中......

### ISSUE THREAD

**Issue by ssszzza** [Alpaca4610/nonebot-plugin-xinghuo-api#10]
就是这样

**Comment by ssszzza** [comment]
![Uploading Screenshot_2024-01-29-10-47-54-24_9d26c6446fd7bb8e41d99b6262b17def.jpg…]()

**Comment by ssszzza** [comment]
![Uploading Screenshot_2024-01-29-10-47-49-42_2665fb67b16260a8d818298cef8dc107.jpg…]()

**Comment by Alpaca4610** [comment]
图片挂了，再上传一次吧

**Comment by ssszzza** [comment]
![Screenshot_2024-01-29-10-47-49-42_2665fb67b16260a8d818298cef8dc107](https://github.com/Alpaca4610/nonebot-plugin-xinghuo-api/assets/117803055/ab17af74-8dae-4710-8f0d-2b0c650ec0ad)

**Comment by ssszzza** [comment]
![Uploading Screenshot_2024-01-29-10-47-54-24_9d26c6446fd7bb8e41d99b6262b17def.jpg…]()

**Comment by ssszzza** [comment]
![Screenshot_2024-01-29-10-47-54-24_9d26c6446fd7bb8e41d99b6262b17def](https://github.com/Alpaca4610/nonebot-plugin-xinghuo-api/assets/117803055/1d3fe5ce-826f-453d-9c25-d3d6d8a01258)

**Comment by Alpaca4610** [comment]
你使用的插件是目前仓库的最新版吗？另外看一下你的配置文件里关于讯飞星火的配置项，敏感信息记得打码。

**Comment by Alpaca4610** [comment]
配置文件中加入`xinghuo_api_version = "v2"`，使用讯飞星火2.0版本进行回答即可解决
