### ISSUE TITLE
请求4.0 Ultra 和3.5的支持

### ISSUE THREAD

**Issue by XokoukioX** [Alpaca4610/nonebot-plugin-xinghuo-api#14]
尝试填入v4，v3, v3.5均无回复，故提出issue

**Comment by Alpaca4610** [comment]
👌🏻

**Comment by Alpaca4610** [comment]
https://github.com/Alpaca4610/nonebot-plugin-xinghuo-api/commit/1f033326a9281eb653aaf300e71efd0f527d2a92
已支持，注意插件可能会与LittlePaimon机器人冲突
