### ISSUE TITLE
new feature

### ISSUE THREAD

**Issue by ThelevenFD** [Alpaca4610/nonebot-plugin-xinghuo-api#16]
添加人物参数

**Comment by ThelevenFD** [comment]
是的是的（有点没表述清楚

**Comment by Alpaca4610** [comment]
已更新https://github.com/Alpaca4610/nonebot-plugin-xinghuo-api/commit/cfc0756a004be5d5ee5c3c18d5ca592def43ae45

**Comment by ThelevenFD** [comment]
已测试，无明显bug，感谢！！
