### ISSUE TITLE
2.0出来了要怎么切换呀

### ISSUE THREAD

**Issue by 983394178** [Alpaca4610/nonebot-plugin-xinghuo-api#2]
2.0出来了要怎么切换呀

**Comment by Alpaca4610** [comment]
等我更新一下代码

**Comment by Alpaca4610** [comment]
现在就要用的话，可以尝试把代码里导入的spark_ai_sdk依赖中的URL改成2.0的

**Comment by 983394178** [comment]
好嘞感谢

**Comment by Alpaca4610** [comment]
> 好嘞感谢

已更新 不过星火2.0的API好像有问题，问几次就出错了

**Comment by mmmjie** [comment]
我用2.0的url 好像会直接复读我的问题。。

**Comment by Alpaca4610** [comment]
> 我用2.0的url 好像会直接复读我的问题。。

我也出现了这个问题，我查了一下后台的报错码是科大讯飞的内部引擎错误，目前我也正在解决这个问题。

**Comment by Alpaca4610** [comment]
> 我用2.0的url 好像会直接复读我的问题。。

已解决
